/**
 * Hand-written barrel re-exporting the generated clients for both contracts under
 * distinct namespaces. `komunify.ts` and `usdc.ts` are generated by `make bindings`
 * (`stellar contract bindings typescript`) and are overwritten on every run — never
 * put hand-written code in them. This file is never touched by that command.
 */
import * as Komunify from "./komunify.js";
import * as Usdc from "./usdc.js";

export { Komunify, Usdc };

// Re-exported once here (both generated files also export these; harmless to pick either).
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";
